services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - mai-home-network

  nginx:
    container_name: nginx
    image: nginx:1.25-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./cert:/etc/nginx/cert
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

networks:
  mai-home-network:
    name: mai-home-network
    driver: bridge
